apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/blender-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - "/redis-config/redis.conf"
          image: redis:latest
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /redis-config
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
status: {}
