---
apiVersion: v1
kind: Service
metadata:
  name: passport
  labels:
    app: passport
    service: passport
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      name: http
  selector:
    app: passport
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: passport-svc
  labels:
    account: passport
---
