---
apiVersion: v1
kind: Service
metadata:
  name: argon-server
  labels:
    app: argon-server
    service: argon-server
spec:
  type: ClusterIP
  selector:
    app: argon-server
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argon-server-svc
  labels:
    account: argon-server
---
