apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-argon-server
  name: db-argon-server
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: db-argon-server
