apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openutm

images:
  - name: argon-server
    newName: registry.digitalocean.com/utmtest/argon-server:latest
    # newName: openskiessh/argon-server:latest


generatorOptions:
  disableNameSuffixHash: true # this flag is used to avoid creation of new configmap, instead it will be modified when file context is changed

configMapGenerator:
  - name: redis-argon-server-config
    files:
      - redis.conf

secretGenerator:
  - name: env-secrets-argon-server
    envs:
      - .env.argon-server

resources:
  - argon-server.yaml
  - argon-server-service.yaml
  - worker.yaml
  - beat.yaml
  - db-argon-server.yaml
  - db-argon-server-pvc.yaml
  - db-argon-server-service.yaml
  - redis-argon-server.yaml
  - redis-argon-server-service.yaml
