apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tile38
  name: tile38
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tile38
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/blender-default: "true"
        io.kompose.service: tile38
    spec:
      containers:
        - args:
            - tile38-server
          image: tile38/tile38
          imagePullPolicy: IfNotPresent
          name: tile38
          ports:
            - containerPort: 9851
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
