---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    service: web
spec:
  type: NodePort
  ports:
    - port: 5000
      name: http
      targetPort: 5000
  selector:
    app: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spotlight-web
  labels:
    account: web
---
