apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openutm

images:
  - name: flight-spotlight    
    newName: openutm/flight-spotlight:latest

generatorOptions:
  disableNameSuffixHash: true # this flag is used to avoid creation of new configmap, instead it will be modified when file context is changed

configMapGenerator:
  - name: redis-spotlight-config
    files:
      - redis.conf

secretGenerator:
  - name: env-secrets-spotlight
    envs:
      - .env.spotlight

resources:
  - spotlight.yaml
  - spotlight-service.yaml
  - tile38.yaml
  - tile38-service.yaml
  - redis-spotlight.yaml
  - redis-spotlight-service.yaml
