---
apiVersion: v1
kind: Service
metadata:
  name: spotlight
  labels:
    app: spotlight
    service: spotlight
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: http
      targetPort: 5000
  selector:
    app: spotlight
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spotlight-svc
  labels:
    account: spotlight
---
