apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-passport-data
  name: db-passport-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
