apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-passport
  name: db-passport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-passport
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/blender-default: "true"
        app: db-passport
    spec:
      containers:
        - env:
            - name: PGDATA
              valueFrom:
                secretKeyRef:
                  key: PGDATA
                  name: env-secrets-passport
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: env-secrets-passport
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: env-secrets-passport
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-secrets-passport
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: env-secrets-passport
          image: postgres
          imagePullPolicy: IfNotPresent
          name: db-passport
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-passport-data
      restartPolicy: Always
      volumes:
        - name: db-passport-data
          persistentVolumeClaim:
            claimName: db-passport-data
status: {}
