---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    service: web
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      name: http
  selector:
    app: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: passport-web
  labels:
    account: web
---
