apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      serviceAccountName: passport-web
      containers:
        - args:
            - ./entrypoint.sh
          name: web
          image: flight-passport
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
          resources: {}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: env-secrets
            - name: PGDATA
              valueFrom:
                secretKeyRef:
                  key: PGDATA
                  name: env-secrets
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: env-secrets
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: env-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: env-secrets
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: env-secrets
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SUPERUSER_USERNAME
                  name: env-secrets
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SUPERUSER_EMAIL
                  name: env-secrets
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SUPERUSER_PASSWORD
                  name: env-secrets
            - name: SHOW_ADMIN
              valueFrom:
                secretKeyRef:
                  key: SHOW_ADMIN
                  name: env-secrets
            - name: USING_DOCKER_COMPOSE
              valueFrom:
                secretKeyRef:
                  key: USING_DOCKER_COMPOSE
                  name: env-secrets
            - name: ENABLE_DEBUG
              valueFrom:
                secretKeyRef:
                  key: ENABLE_DEBUG
                  name: env-secrets
      imagePullSecrets:
        - name: registry-utmtest
