apiVersion: apps/v1
kind: Deployment
metadata:
  name: blender
  labels:
    app: blender
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blender
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blender
        version: v1
    spec:
      serviceAccountName: blender-svc
      containers:
        - name: blender
          command:
            - ./entrypoints/with-database/entrypoint.sh
          image: flight-blender
          # imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources: {}
          env:
            - name: POSTGRES_HOST
              value: "db-blender"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: env-secrets-blender
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: env-secrets-blender
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-secrets-blender
            - name: DATABASE_URL
              value: "pgsql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: env-secrets-blender
            - name: BLENDER_FQDN
              valueFrom:
                secretKeyRef:
                  key: BLENDER_FQDN
                  name: env-secrets-blender
            - name: BYPASS_AUTH_TOKEN_VERIFICATION
              valueFrom:
                secretKeyRef:
                  key: BYPASS_AUTH_TOKEN_VERIFICATION
                  name: env-secrets-blender
            - name: HEARTBEAT_RATE_SECS
              valueFrom:
                secretKeyRef:
                  key: HEARTBEAT_RATE_SECS
                  name: env-secrets-blender
            - name: IS_DEBUG
              valueFrom:
                secretKeyRef:
                  key: IS_DEBUG
                  name: env-secrets-blender
            - name: PASSPORT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  key: PASSPORT_AUDIENCE
                  name: env-secrets-blender
            - name: PASSPORT_URL
              valueFrom:
                secretKeyRef:
                  key: PASSPORT_URL
                  name: env-secrets-blender
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: env-secrets-blender
            - name: REDIS_HOST
              value: "redis-blender"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_BROKER_URL
              value: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)"
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  key: DJANGO_LOG_LEVEL
                  name: env-secrets-blender
      imagePullSecrets:
        - name: registry-utmtest
