---
apiVersion: v1
kind: Service
metadata:
  name: blender
  labels:
    app: blender
    service: blender
spec:
  type: ClusterIP
  selector:
    app: blender
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blender-svc
  labels:
    account: blender
---
