apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-flight-blender-data
  name: db-flight-blender-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
