apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-flight-blender
  name: db-flight-blender
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: db-flight-blender
