apiVersion: v1
kind: Service
metadata:
  name: redis-blender
  labels:
    app: redis-blender
    service: redis-blender
spec:
  type: ClusterIP
  selector:
    app: redis-blender
  ports:
    - name: redis
      port: 6379
      targetPort: redis
