apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-nginx-root
  namespace: openutm
  # Cert-Manager will put the resulting Secret in the same Kubernetes namespace as the Certificate.
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: letsencrypt-nginx-root-tls
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-nginx-issuer
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "${DOMAIN_NAME}"
  # List of DNS subjectAltNames to be set on the Certificate.
  dnsNames:
    - "${DOMAIN_NAME}"
