apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-spotlight
  name: redis-spotlight
spec:
  type: ClusterIP
  selector:
    app: redis-spotlight
  ports:
    - name: redis
      port: 6379
      targetPort: redis
