apiVersion: v1
kind: Service
metadata:
  labels:
    app: tile38
  name: tile38
spec:
  ports:
    - port: 9851
      name: tile38
      targetPort: 9851
  selector:
    app: tile38
status:
  loadBalancer: {}
