apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: passport

images:
  - name: flight-passport
    newName: registry.digitalocean.com/utmtest/flight-passport:latest

generatorOptions:
  disableNameSuffixHash: true # this flag is used to avoid creation of new configmap, instead it will be modified when file context is changed

secretGenerator:
  - name: env-secrets
    envs:
      - .env

resources:
  - resources/namespace.yaml
  - resources/web.yaml
  - resources/web-service.yaml
  - resources/db.yaml
  - resources/db-pvc.yaml
  - resources/db-service.yaml
